project:
  title: "2023-nsf-career"
  output-dir: docs
  render:
    - 1pg-summary.qmd

    - Index.qmd
    - Bio.qmd
    - Budget.qmd
    - Collaborators.qmd
    - Data.qmd
    # - PostdocPlan.qmd
    - ProjectDescription.qmd
    - Resources.qmd
    - Summary.qmd

  preview:
    port: 4200
    browser: true

format:
  pdf:
    keep-tex: false
    number-sections: true
    documentclass: scrartcl
    fontsize: 11pt
    papersize: letter
    toc: false
    geometry:
      - top=1in
      - left=1in
      - right=1in
      - bottom=1in
    include-in-header: style/preamble.tex
  # html:
  #   toc: true
  #   html-math-method: katex

# bibliography: refs.bib

csl: style/national-science-foundation-grant-proposals.csl

